;; AUTO-GENERATED FILE
;; Can generate with the following command at root of quaint source tree:
;; python3 goodies/emacs/gencodec.py goodies/emacs/quaint-codec-data.el

(setq quaint-codec-delim-start "`")
(setq quaint-codec-delim-end "`")

;; List of digraphs used in quaint
;; (digraph . character_code) ;; the character
(setq quaint-codec-digraphs-list '(
    ("<>" . #x2666) ;; ♦
    ("<<" . #x00ab) ;; «
    ("<=" . #x21d0) ;; ⇐
    ("<-" . #x2190) ;; ←
    ("=<" . #x2264) ;; ≤
    (">=" . #x2265) ;; ≥
    (">>" . #x00bb) ;; »
    ("=>" . #x21d2) ;; ⇒
    ("->" . #x2192) ;; →
    ("~~" . #x2248) ;; ≈
    ("~=" . #x2245) ;; ≅
    ("/=" . #x2260) ;; ≠
    ("|-" . #x22a6) ;; ⊦
    ("|=" . #x22a7) ;; ⊧
    ("``" . #x0060) ;; `
    ("``" . #x0060) ;; `
))

;; List of named codes used in quaint, without the surrounding backslashes.
;; Typing \identifier\ encodes the character. A literal backslash is \\.
;; (identifier . character_code) ;; the character
(setq quaint-codec-named-codes-list '(
    ("A'"                   . #x00c1) ;; Á
    ("Aac"                  . #x00c1) ;; Á
    ("Aacute"               . #x00c1) ;; Á
    ("a'"                   . #x00e1) ;; á
    ("aac"                  . #x00e1) ;; á
    ("aacute"               . #x00e1) ;; á
    ("A^"                   . #x00c2) ;; Â
    ("Aci"                  . #x00c2) ;; Â
    ("Acirc"                . #x00c2) ;; Â
    ("a^"                   . #x00e2) ;; â
    ("aci"                  . #x00e2) ;; â
    ("acirc"                . #x00e2) ;; â
    ("acute"                . #x00b4) ;; ´
    ("AE"                   . #x00c6) ;; Æ
    ("AElig"                . #x00c6) ;; Æ
    ("ae"                   . #x00e6) ;; æ
    ("aelig"                . #x00e6) ;; æ
    ("A\"                   . #x00c0) ;; À
    ("Agr"                  . #x00c0) ;; À
    ("Agrave"               . #x00c0) ;; À
    ("a\"                   . #x00e0) ;; à
    ("agr"                  . #x00e0) ;; à
    ("agrave"               . #x00e0) ;; à
    ("alefsym"              . #x2135) ;; ℵ
    ("Alpha"                . #x0391) ;; Α
    ("alpha"                . #x03b1) ;; α
    ("amp"                  . #x0026) ;; &
    ("and"                  . #x2227) ;; ∧
    ("wedge"                . #x2227) ;; ∧
    ("ang"                  . #x2220) ;; ∠
    ("Aring"                . #x00c5) ;; Å
    ("aring"                . #x00e5) ;; å
    ("asymp"                . #x2248) ;; ≈
    ("A~"                   . #x00c3) ;; Ã
    ("Ati"                  . #x00c3) ;; Ã
    ("Atilde"               . #x00c3) ;; Ã
    ("a~"                   . #x00e3) ;; ã
    ("ati"                  . #x00e3) ;; ã
    ("atilde"               . #x00e3) ;; ã
    ("A\""                  . #x00c4) ;; Ä
    ("Aum"                  . #x00c4) ;; Ä
    ("Auml"                 . #x00c4) ;; Ä
    ("a\""                  . #x00e4) ;; ä
    ("aum"                  . #x00e4) ;; ä
    ("auml"                 . #x00e4) ;; ä
    ("bdquo"                . #x201e) ;; „
    ("Beta"                 . #x0392) ;; Β
    ("beta"                 . #x03b2) ;; β
    ("brvbar"               . #x00a6) ;; ¦
    ("b"                    . #x2022) ;; •
    ("bull"                 . #x2022) ;; •
    ("intersection"         . #x2229) ;; ∩
    ("cap"                  . #x2229) ;; ∩
    ("Cc"                   . #x00c7) ;; Ç
    ("Ccedil"               . #x00c7) ;; Ç
    ("cc"                   . #x00e7) ;; ç
    ("ccedil"               . #x00e7) ;; ç
    ("cedil"                . #x00b8) ;; ¸
    ("cent"                 . #x00a2) ;; ¢
    ("Chi"                  . #x03a7) ;; Χ
    ("chi"                  . #x03c7) ;; χ
    ("circ"                 . #x02c6) ;; ˆ
    ("club"                 . #x2663) ;; ♣
    ("clubs"                . #x2663) ;; ♣
    ("cong"                 . #x2245) ;; ≅
    ("copy"                 . #x00a9) ;; ©
    ("crarr"                . #x21b5) ;; ↵
    ("union"                . #x222a) ;; ∪
    ("cup"                  . #x222a) ;; ∪
    ("curren"               . #x00a4) ;; ¤
    ("Dagger"               . #x2021) ;; ‡
    ("dagger"               . #x2020) ;; †
    ("Down"                 . #x21d3) ;; ⇓
    ("dArr"                 . #x21d3) ;; ⇓
    ("down"                 . #x2193) ;; ↓
    ("darr"                 . #x2193) ;; ↓
    ("deg"                  . #x00b0) ;; °
    ("degree"               . #x00b0) ;; °
    ("Delta"                . #x0394) ;; Δ
    ("delta"                . #x03b4) ;; δ
    ("diamond"              . #x2666) ;; ♦
    ("diamonds"             . #x2666) ;; ♦
    ("diams"                . #x2666) ;; ♦
    ("divide"               . #x00f7) ;; ÷
    ("E'"                   . #x00c9) ;; É
    ("Eac"                  . #x00c9) ;; É
    ("Eacute"               . #x00c9) ;; É
    ("e'"                   . #x00e9) ;; é
    ("eac"                  . #x00e9) ;; é
    ("eacute"               . #x00e9) ;; é
    ("E^"                   . #x00ca) ;; Ê
    ("Eci"                  . #x00ca) ;; Ê
    ("Ecirc"                . #x00ca) ;; Ê
    ("e^"                   . #x00ea) ;; ê
    ("eci"                  . #x00ea) ;; ê
    ("ecirc"                . #x00ea) ;; ê
    ("E\"                   . #x00c8) ;; È
    ("Egr"                  . #x00c8) ;; È
    ("Egrave"               . #x00c8) ;; È
    ("e\"                   . #x00e8) ;; è
    ("egr"                  . #x00e8) ;; è
    ("egrave"               . #x00e8) ;; è
    ("empty"                . #x2205) ;; ∅
    ("emsp"                 . #x2003) ;;  
    ("ensp"                 . #x2002) ;;  
    ("Epsilon"              . #x0395) ;; Ε
    ("epsilon"              . #x03b5) ;; ε
    ("equiv"                . #x2261) ;; ≡
    ("Eta"                  . #x0397) ;; Η
    ("eta"                  . #x03b7) ;; η
    ("ETH"                  . #x00d0) ;; Ð
    ("eth"                  . #x00f0) ;; ð
    ("E\""                  . #x00cb) ;; Ë
    ("Eum"                  . #x00cb) ;; Ë
    ("Euml"                 . #x00cb) ;; Ë
    ("e\""                  . #x00eb) ;; ë
    ("eum"                  . #x00eb) ;; ë
    ("euml"                 . #x00eb) ;; ë
    ("euro"                 . #x20ac) ;; €
    ("exists"               . #x2203) ;; ∃
    ("exist"                . #x2203) ;; ∃
    ("fnof"                 . #x0192) ;; ƒ
    ("forall"               . #x2200) ;; ∀
    ("frac12"               . #x00bd) ;; ½
    ("frac14"               . #x00bc) ;; ¼
    ("frac34"               . #x00be) ;; ¾
    ("frasl"                . #x2044) ;; ⁄
    ("Gamma"                . #x0393) ;; Γ
    ("gamma"                . #x03b3) ;; γ
    ("ge"                   . #x2265) ;; ≥
    ("gt"                   . #x003e) ;; >
    ("LeftRight"            . #x21d4) ;; ⇔
    ("hArr"                 . #x21d4) ;; ⇔
    ("leftright"            . #x2194) ;; ↔
    ("harr"                 . #x2194) ;; ↔
    ("heart"                . #x2665) ;; ♥
    ("hearts"               . #x2665) ;; ♥
    ("to"                   . #x2025) ;; ‥
    ("hellip"               . #x2026) ;; …
    ("I'"                   . #x00cd) ;; Í
    ("Iac"                  . #x00cd) ;; Í
    ("Iacute"               . #x00cd) ;; Í
    ("i'"                   . #x00ed) ;; í
    ("iac"                  . #x00ed) ;; í
    ("iacute"               . #x00ed) ;; í
    ("I^"                   . #x00ce) ;; Î
    ("Ici"                  . #x00ce) ;; Î
    ("Icirc"                . #x00ce) ;; Î
    ("i^"                   . #x00ee) ;; î
    ("ici"                  . #x00ee) ;; î
    ("icirc"                . #x00ee) ;; î
    ("iexcl"                . #x00a1) ;; ¡
    ("I\"                   . #x00cc) ;; Ì
    ("Igr"                  . #x00cc) ;; Ì
    ("Igrave"               . #x00cc) ;; Ì
    ("i\"                   . #x00ec) ;; ì
    ("igr"                  . #x00ec) ;; ì
    ("igrave"               . #x00ec) ;; ì
    ("image"                . #x2111) ;; ℑ
    ("infinity"             . #x221e) ;; ∞
    ("infin"                . #x221e) ;; ∞
    ("infty"                . #x221e) ;; ∞
    ("integral"             . #x222b) ;; ∫
    ("int"                  . #x222b) ;; ∫
    ("Iota"                 . #x0399) ;; Ι
    ("iota"                 . #x03b9) ;; ι
    ("iquest"               . #x00bf) ;; ¿
    ("in"                   . #x2208) ;; ∈
    ("isin"                 . #x2208) ;; ∈
    ("I\""                  . #x00cf) ;; Ï
    ("Ium"                  . #x00cf) ;; Ï
    ("Iuml"                 . #x00cf) ;; Ï
    ("i\""                  . #x00ef) ;; ï
    ("ium"                  . #x00ef) ;; ï
    ("iuml"                 . #x00ef) ;; ï
    ("Kappa"                . #x039a) ;; Κ
    ("kappa"                . #x03ba) ;; κ
    ("Lambda"               . #x039b) ;; Λ
    ("lambda"               . #x03bb) ;; λ
    ("lang"                 . #x2329) ;; 〈
    ("laquo"                . #x00ab) ;; «
    ("Left"                 . #x21d0) ;; ⇐
    ("lArr"                 . #x21d0) ;; ⇐
    ("left"                 . #x2190) ;; ←
    ("larr"                 . #x2190) ;; ←
    ("lceil"                . #x2308) ;; ⌈
    ("ldquo"                . #x201c) ;; “
    ("le"                   . #x2264) ;; ≤
    ("lfloor"               . #x230a) ;; ⌊
    ("lowast"               . #x2217) ;; ∗
    ("loz"                  . #x25ca) ;; ◊
    ("lrm"                  . #x200e) ;; ‎
    ("lsaquo"               . #x2039) ;; ‹
    ("lsquo"                . #x2018) ;; ‘
    ("lt"                   . #x003c) ;; <
    ("macr"                 . #x00af) ;; ¯
    ("mdash"                . #x2014) ;; —
    ("micro"                . #x00b5) ;; µ
    ("middot"               . #x00b7) ;; ·
    ("minus"                . #x2212) ;; −
    ("Mu"                   . #x039c) ;; Μ
    ("mu"                   . #x03bc) ;; μ
    ("gradient"             . #x2207) ;; ∇
    ("nabla"                . #x2207) ;; ∇
    ("nbsp"                 . #x00a0) ;;  
    ("ndash"                . #x2013) ;; –
    ("ne"                   . #x2260) ;; ≠
    ("ni"                   . #x220b) ;; ∋
    ("not"                  . #x00ac) ;; ¬
    ("notin"                . #x2209) ;; ∉
    ("nsub"                 . #x2284) ;; ⊄
    ("N~"                   . #x00d1) ;; Ñ
    ("Nti"                  . #x00d1) ;; Ñ
    ("Ntilde"               . #x00d1) ;; Ñ
    ("n~"                   . #x00f1) ;; ñ
    ("nti"                  . #x00f1) ;; ñ
    ("ntilde"               . #x00f1) ;; ñ
    ("Nu"                   . #x039d) ;; Ν
    ("nu"                   . #x03bd) ;; ν
    ("O'"                   . #x00d3) ;; Ó
    ("Oac"                  . #x00d3) ;; Ó
    ("Oacute"               . #x00d3) ;; Ó
    ("o'"                   . #x00f3) ;; ó
    ("oac"                  . #x00f3) ;; ó
    ("oacute"               . #x00f3) ;; ó
    ("O^"                   . #x00d4) ;; Ô
    ("Oci"                  . #x00d4) ;; Ô
    ("Ocirc"                . #x00d4) ;; Ô
    ("o^"                   . #x00f4) ;; ô
    ("oci"                  . #x00f4) ;; ô
    ("ocirc"                . #x00f4) ;; ô
    ("OE"                   . #x0152) ;; Œ
    ("OElig"                . #x0152) ;; Œ
    ("oe"                   . #x0153) ;; œ
    ("oelig"                . #x0153) ;; œ
    ("O\"                   . #x00d2) ;; Ò
    ("Ogr"                  . #x00d2) ;; Ò
    ("Ograve"               . #x00d2) ;; Ò
    ("o\"                   . #x00f2) ;; ò
    ("ogr"                  . #x00f2) ;; ò
    ("ograve"               . #x00f2) ;; ò
    ("oline"                . #x203e) ;; ‾
    ("Omega"                . #x03a9) ;; Ω
    ("omega"                . #x03c9) ;; ω
    ("Omicron"              . #x039f) ;; Ο
    ("omicron"              . #x03bf) ;; ο
    ("oplus"                . #x2295) ;; ⊕
    ("or"                   . #x2228) ;; ∨
    ("vee"                  . #x2228) ;; ∨
    ("ordf"                 . #x00aa) ;; ª
    ("ordm"                 . #x00ba) ;; º
    ("Oslash"               . #x00d8) ;; Ø
    ("oslash"               . #x00f8) ;; ø
    ("O~"                   . #x00d5) ;; Õ
    ("Oti"                  . #x00d5) ;; Õ
    ("Otilde"               . #x00d5) ;; Õ
    ("o~"                   . #x00f5) ;; õ
    ("oti"                  . #x00f5) ;; õ
    ("otilde"               . #x00f5) ;; õ
    ("otimes"               . #x2297) ;; ⊗
    ("O\""                  . #x00d6) ;; Ö
    ("Oum"                  . #x00d6) ;; Ö
    ("Ouml"                 . #x00d6) ;; Ö
    ("o\""                  . #x00f6) ;; ö
    ("oum"                  . #x00f6) ;; ö
    ("ouml"                 . #x00f6) ;; ö
    ("para"                 . #x00b6) ;; ¶
    ("part"                 . #x2202) ;; ∂
    ("permil"               . #x2030) ;; ‰
    ("perp"                 . #x22a5) ;; ⊥
    ("Phi"                  . #x03a6) ;; Φ
    ("phi"                  . #x03c6) ;; φ
    ("Pi"                   . #x03a0) ;; Π
    ("pi"                   . #x03c0) ;; π
    ("piv"                  . #x03d6) ;; ϖ
    ("pm"                   . #x00b1) ;; ±
    ("plusmn"               . #x00b1) ;; ±
    ("pound"                . #x00a3) ;; £
    ("Prime"                . #x2033) ;; ″
    ("prime"                . #x2032) ;; ′
    ("prod"                 . #x220f) ;; ∏
    ("prop"                 . #x221d) ;; ∝
    ("Psi"                  . #x03a8) ;; Ψ
    ("psi"                  . #x03c8) ;; ψ
    ("quot"                 . #x0022) ;; "
    ("radic"                . #x221a) ;; √
    ("rang"                 . #x232a) ;; 〉
    ("raquo"                . #x00bb) ;; »
    ("Right"                . #x21d2) ;; ⇒
    ("rArr"                 . #x21d2) ;; ⇒
    ("right"                . #x2192) ;; →
    ("rarr"                 . #x2192) ;; →
    ("rceil"                . #x2309) ;; ⌉
    ("rdquo"                . #x201d) ;; ”
    ("real"                 . #x211c) ;; ℜ
    ("reg"                  . #x00ae) ;; ®
    ("rfloor"               . #x230b) ;; ⌋
    ("Rho"                  . #x03a1) ;; Ρ
    ("rho"                  . #x03c1) ;; ρ
    ("rlm"                  . #x200f) ;; ‏
    ("rsaquo"               . #x203a) ;; ›
    ("rsquo"                . #x2019) ;; ’
    ("sbquo"                . #x201a) ;; ‚
    ("Scaron"               . #x0160) ;; Š
    ("scaron"               . #x0161) ;; š
    ("sdot"                 . #x22c5) ;; ⋅
    ("sect"                 . #x00a7) ;; §
    ("shy"                  . #x00ad) ;; ­
    ("Sigma"                . #x03a3) ;; Σ
    ("sigma"                . #x03c3) ;; σ
    ("sigmaf"               . #x03c2) ;; ς
    ("sim"                  . #x223c) ;; ∼
    ("spade"                . #x2660) ;; ♠
    ("spades"               . #x2660) ;; ♠
    ("subset"               . #x2282) ;; ⊂
    ("sub"                  . #x2282) ;; ⊂
    ("subseteq"             . #x2286) ;; ⊆
    ("sube"                 . #x2286) ;; ⊆
    ("sum"                  . #x2211) ;; ∑
    ("supset"               . #x2283) ;; ⊃
    ("sup"                  . #x2283) ;; ⊃
    ("sup1"                 . #x00b9) ;; ¹
    ("sup2"                 . #x00b2) ;; ²
    ("sup3"                 . #x00b3) ;; ³
    ("supseteq"             . #x2287) ;; ⊇
    ("supe"                 . #x2287) ;; ⊇
    ("ss"                   . #x00df) ;; ß
    ("szlig"                . #x00df) ;; ß
    ("Tau"                  . #x03a4) ;; Τ
    ("tau"                  . #x03c4) ;; τ
    ("there4"               . #x2234) ;; ∴
    ("Theta"                . #x0398) ;; Θ
    ("theta"                . #x03b8) ;; θ
    ("thetasym"             . #x03d1) ;; ϑ
    ("thinsp"               . #x2009) ;;  
    ("THORN"                . #x00de) ;; Þ
    ("thorn"                . #x00fe) ;; þ
    ("tilde"                . #x02dc) ;; ˜
    ("times"                . #x00d7) ;; ×
    ("trade"                . #x2122) ;; ™
    ("U'"                   . #x00da) ;; Ú
    ("Uac"                  . #x00da) ;; Ú
    ("Uacute"               . #x00da) ;; Ú
    ("u'"                   . #x00fa) ;; ú
    ("uac"                  . #x00fa) ;; ú
    ("uacute"               . #x00fa) ;; ú
    ("Up"                   . #x21d1) ;; ⇑
    ("uArr"                 . #x21d1) ;; ⇑
    ("up"                   . #x2191) ;; ↑
    ("uarr"                 . #x2191) ;; ↑
    ("U^"                   . #x00db) ;; Û
    ("Uci"                  . #x00db) ;; Û
    ("Ucirc"                . #x00db) ;; Û
    ("u^"                   . #x00fb) ;; û
    ("uci"                  . #x00fb) ;; û
    ("ucirc"                . #x00fb) ;; û
    ("U\"                   . #x00d9) ;; Ù
    ("Ugr"                  . #x00d9) ;; Ù
    ("Ugrave"               . #x00d9) ;; Ù
    ("u\"                   . #x00f9) ;; ù
    ("ugr"                  . #x00f9) ;; ù
    ("ugrave"               . #x00f9) ;; ù
    ("uml"                  . #x00a8) ;; ¨
    ("upsih"                . #x03d2) ;; ϒ
    ("Upsilon"              . #x03a5) ;; Υ
    ("upsilon"              . #x03c5) ;; υ
    ("U\""                  . #x00dc) ;; Ü
    ("Uum"                  . #x00dc) ;; Ü
    ("Uuml"                 . #x00dc) ;; Ü
    ("u\""                  . #x00fc) ;; ü
    ("uum"                  . #x00fc) ;; ü
    ("uuml"                 . #x00fc) ;; ü
    ("weierp"               . #x2118) ;; ℘
    ("Xi"                   . #x039e) ;; Ξ
    ("xi"                   . #x03be) ;; ξ
    ("Y'"                   . #x00dd) ;; Ý
    ("Yac"                  . #x00dd) ;; Ý
    ("Yacute"               . #x00dd) ;; Ý
    ("y'"                   . #x00fd) ;; ý
    ("yac"                  . #x00fd) ;; ý
    ("yacute"               . #x00fd) ;; ý
    ("yen"                  . #x00a5) ;; ¥
    ("Y\""                  . #x0178) ;; Ÿ
    ("Yum"                  . #x0178) ;; Ÿ
    ("Yuml"                 . #x0178) ;; Ÿ
    ("y\""                  . #x00ff) ;; ÿ
    ("yum"                  . #x00ff) ;; ÿ
    ("yuml"                 . #x00ff) ;; ÿ
    ("Zeta"                 . #x0396) ;; Ζ
    ("zeta"                 . #x03b6) ;; ζ
    ("zwj"                  . #x200d) ;; ‍
    ("zwnj"                 . #x200c) ;; ‌
    ("complex"              . #x2102) ;; ℂ
    ("reals"                . #x211d) ;; ℝ
    ("rationals"            . #x211a) ;; ℚ
    ("naturals"             . #x2115) ;; ℕ
    ("integers"             . #x2124) ;; ℤ
    ("xor"                  . #x22bb) ;; ⊻
    ("nor"                  . #x22bd) ;; ⊽
    ("nand"                 . #x22bc) ;; ⊼
    ("after"                . #x2218) ;; ∘
    ("circle"               . #x2218) ;; ∘
    ("cw"                   . #x21bb) ;; ↻
    ("clockw"               . #x21bb) ;; ↻
    ("clockwise"            . #x21bb) ;; ↻
    ("ccw"                  . #x21ba) ;; ↺
    ("cclockw"              . #x21ba) ;; ↺
    ("counterclockwise"     . #x21ba) ;; ↺
    ("UpDown"               . #x21d5) ;; ⇕
    ("vArr"                 . #x21d5) ;; ⇕
    ("updown"               . #x2195) ;; ↕
    ("varr"                 . #x2195) ;; ↕
    ("asserts"              . #x22a6) ;; ⊦
    ("models"               . #x22a7) ;; ⊧
    ("br"                   . #x21b2) ;; ↲
    ("lf"                   . #x21b2) ;; ↲
    ("tab"                  . #x21b9) ;; ↹
    ("ht"                   . #x21b9) ;; ↹
    ("esc"                  . #x23cf) ;; ⏏
    (">"                    . #x003e) ;; >
    ("<"                    . #x003c) ;; <
    ("-"                    . #x002d) ;; -
    ("="                    . #x003d) ;; =
    ("~"                    . #x007e) ;; ~
    ("|"                    . #x007c) ;; |
    ("/"                    . #x002f) ;; /
))

;; Mapping from unicode code points to an encoding.
;; (character_code . encoding) ;; the character
(setq quaint-codec-encode-list '(
    (#x00a0 . "`nbsp`")              ;;  
    (#x00a1 . "`iexcl`")             ;; ¡
    (#x00a2 . "`cent`")              ;; ¢
    (#x00a3 . "`pound`")             ;; £
    (#x00a4 . "`curren`")            ;; ¤
    (#x00a5 . "`yen`")               ;; ¥
    (#x00a6 . "`brvbar`")            ;; ¦
    (#x00a7 . "`sect`")              ;; §
    (#x00a8 . "`uml`")               ;; ¨
    (#x00a9 . "`copy`")              ;; ©
    (#x00aa . "`ordf`")              ;; ª
    (#x00ab . "<<")                  ;; «
    (#x00ac . "`not`")               ;; ¬
    (#x00ad . "`shy`")               ;; ­
    (#x00ae . "`reg`")               ;; ®
    (#x00af . "`macr`")              ;; ¯
    (#x00b0 . "`deg`")               ;; °
    (#x00b1 . "`pm`")                ;; ±
    (#x00b2 . "`sup2`")              ;; ²
    (#x00b3 . "`sup3`")              ;; ³
    (#x00b4 . "`acute`")             ;; ´
    (#x00b5 . "`micro`")             ;; µ
    (#x00b6 . "`para`")              ;; ¶
    (#x00b7 . "`middot`")            ;; ·
    (#x00b8 . "`cedil`")             ;; ¸
    (#x00b9 . "`sup1`")              ;; ¹
    (#x00ba . "`ordm`")              ;; º
    (#x00bb . ">>")                  ;; »
    (#x00bc . "`frac14`")            ;; ¼
    (#x00bd . "`frac12`")            ;; ½
    (#x00be . "`frac34`")            ;; ¾
    (#x00bf . "`iquest`")            ;; ¿
    (#x00c0 . "`A\\`")               ;; À
    (#x00c1 . "`A'`")                ;; Á
    (#x00c2 . "`A^`")                ;; Â
    (#x00c3 . "`A~`")                ;; Ã
    (#x00c4 . "`A\"`")               ;; Ä
    (#x00c5 . "`Aring`")             ;; Å
    (#x00c6 . "`AE`")                ;; Æ
    (#x00c7 . "`Cc`")                ;; Ç
    (#x00c8 . "`E\\`")               ;; È
    (#x00c9 . "`E'`")                ;; É
    (#x00ca . "`E^`")                ;; Ê
    (#x00cb . "`E\"`")               ;; Ë
    (#x00cc . "`I\\`")               ;; Ì
    (#x00cd . "`I'`")                ;; Í
    (#x00ce . "`I^`")                ;; Î
    (#x00cf . "`I\"`")               ;; Ï
    (#x00d0 . "`ETH`")               ;; Ð
    (#x00d1 . "`N~`")                ;; Ñ
    (#x00d2 . "`O\\`")               ;; Ò
    (#x00d3 . "`O'`")                ;; Ó
    (#x00d4 . "`O^`")                ;; Ô
    (#x00d5 . "`O~`")                ;; Õ
    (#x00d6 . "`O\"`")               ;; Ö
    (#x00d7 . "`times`")             ;; ×
    (#x00d8 . "`Oslash`")            ;; Ø
    (#x00d9 . "`U\\`")               ;; Ù
    (#x00da . "`U'`")                ;; Ú
    (#x00db . "`U^`")                ;; Û
    (#x00dc . "`U\"`")               ;; Ü
    (#x00dd . "`Y'`")                ;; Ý
    (#x00de . "`THORN`")             ;; Þ
    (#x00df . "`ss`")                ;; ß
    (#x00e0 . "`a\\`")               ;; à
    (#x00e1 . "`a'`")                ;; á
    (#x00e2 . "`a^`")                ;; â
    (#x00e3 . "`a~`")                ;; ã
    (#x00e4 . "`a\"`")               ;; ä
    (#x00e5 . "`aring`")             ;; å
    (#x00e6 . "`ae`")                ;; æ
    (#x00e7 . "`cc`")                ;; ç
    (#x00e8 . "`e\\`")               ;; è
    (#x00e9 . "`e'`")                ;; é
    (#x00ea . "`e^`")                ;; ê
    (#x00eb . "`e\"`")               ;; ë
    (#x00ec . "`i\\`")               ;; ì
    (#x00ed . "`i'`")                ;; í
    (#x00ee . "`i^`")                ;; î
    (#x00ef . "`i\"`")               ;; ï
    (#x00f0 . "`eth`")               ;; ð
    (#x00f1 . "`n~`")                ;; ñ
    (#x00f2 . "`o\\`")               ;; ò
    (#x00f3 . "`o'`")                ;; ó
    (#x00f4 . "`o^`")                ;; ô
    (#x00f5 . "`o~`")                ;; õ
    (#x00f6 . "`o\"`")               ;; ö
    (#x00f7 . "`divide`")            ;; ÷
    (#x00f8 . "`oslash`")            ;; ø
    (#x00f9 . "`u\\`")               ;; ù
    (#x00fa . "`u'`")                ;; ú
    (#x00fb . "`u^`")                ;; û
    (#x00fc . "`u\"`")               ;; ü
    (#x00fd . "`y'`")                ;; ý
    (#x00fe . "`thorn`")             ;; þ
    (#x00ff . "`y\"`")               ;; ÿ
    (#x0152 . "`OE`")                ;; Œ
    (#x0153 . "`oe`")                ;; œ
    (#x0160 . "`Scaron`")            ;; Š
    (#x0161 . "`scaron`")            ;; š
    (#x0178 . "`Y\"`")               ;; Ÿ
    (#x0192 . "`fnof`")              ;; ƒ
    (#x02c6 . "`circ`")              ;; ˆ
    (#x02dc . "`tilde`")             ;; ˜
    (#x0391 . "`Alpha`")             ;; Α
    (#x0392 . "`Beta`")              ;; Β
    (#x0393 . "`Gamma`")             ;; Γ
    (#x0394 . "`Delta`")             ;; Δ
    (#x0395 . "`Epsilon`")           ;; Ε
    (#x0396 . "`Zeta`")              ;; Ζ
    (#x0397 . "`Eta`")               ;; Η
    (#x0398 . "`Theta`")             ;; Θ
    (#x0399 . "`Iota`")              ;; Ι
    (#x039a . "`Kappa`")             ;; Κ
    (#x039b . "`Lambda`")            ;; Λ
    (#x039c . "`Mu`")                ;; Μ
    (#x039d . "`Nu`")                ;; Ν
    (#x039e . "`Xi`")                ;; Ξ
    (#x039f . "`Omicron`")           ;; Ο
    (#x03a0 . "`Pi`")                ;; Π
    (#x03a1 . "`Rho`")               ;; Ρ
    (#x03a3 . "`Sigma`")             ;; Σ
    (#x03a4 . "`Tau`")               ;; Τ
    (#x03a5 . "`Upsilon`")           ;; Υ
    (#x03a6 . "`Phi`")               ;; Φ
    (#x03a7 . "`Chi`")               ;; Χ
    (#x03a8 . "`Psi`")               ;; Ψ
    (#x03a9 . "`Omega`")             ;; Ω
    (#x03b1 . "`alpha`")             ;; α
    (#x03b2 . "`beta`")              ;; β
    (#x03b3 . "`gamma`")             ;; γ
    (#x03b4 . "`delta`")             ;; δ
    (#x03b5 . "`epsilon`")           ;; ε
    (#x03b6 . "`zeta`")              ;; ζ
    (#x03b7 . "`eta`")               ;; η
    (#x03b8 . "`theta`")             ;; θ
    (#x03b9 . "`iota`")              ;; ι
    (#x03ba . "`kappa`")             ;; κ
    (#x03bb . "`lambda`")            ;; λ
    (#x03bc . "`mu`")                ;; μ
    (#x03bd . "`nu`")                ;; ν
    (#x03be . "`xi`")                ;; ξ
    (#x03bf . "`omicron`")           ;; ο
    (#x03c0 . "`pi`")                ;; π
    (#x03c1 . "`rho`")               ;; ρ
    (#x03c2 . "`sigmaf`")            ;; ς
    (#x03c3 . "`sigma`")             ;; σ
    (#x03c4 . "`tau`")               ;; τ
    (#x03c5 . "`upsilon`")           ;; υ
    (#x03c6 . "`phi`")               ;; φ
    (#x03c7 . "`chi`")               ;; χ
    (#x03c8 . "`psi`")               ;; ψ
    (#x03c9 . "`omega`")             ;; ω
    (#x03d1 . "`thetasym`")          ;; ϑ
    (#x03d2 . "`upsih`")             ;; ϒ
    (#x03d6 . "`piv`")               ;; ϖ
    (#x2002 . "`ensp`")              ;;  
    (#x2003 . "`emsp`")              ;;  
    (#x2009 . "`thinsp`")            ;;  
    (#x200c . "`zwnj`")              ;; ‌
    (#x200d . "`zwj`")               ;; ‍
    (#x200e . "`lrm`")               ;; ‎
    (#x200f . "`rlm`")               ;; ‏
    (#x2013 . "`ndash`")             ;; –
    (#x2014 . "`mdash`")             ;; —
    (#x2018 . "`lsquo`")             ;; ‘
    (#x2019 . "`rsquo`")             ;; ’
    (#x201a . "`sbquo`")             ;; ‚
    (#x201c . "`ldquo`")             ;; “
    (#x201d . "`rdquo`")             ;; ”
    (#x201e . "`bdquo`")             ;; „
    (#x2020 . "`dagger`")            ;; †
    (#x2021 . "`Dagger`")            ;; ‡
    (#x2022 . "`b`")                 ;; •
    (#x2025 . "`to`")                ;; ‥
    (#x2026 . "`hellip`")            ;; …
    (#x2030 . "`permil`")            ;; ‰
    (#x2032 . "`prime`")             ;; ′
    (#x2033 . "`Prime`")             ;; ″
    (#x2039 . "`lsaquo`")            ;; ‹
    (#x203a . "`rsaquo`")            ;; ›
    (#x203e . "`oline`")             ;; ‾
    (#x2044 . "`frasl`")             ;; ⁄
    (#x20ac . "`euro`")              ;; €
    (#x2102 . "`complex`")           ;; ℂ
    (#x2111 . "`image`")             ;; ℑ
    (#x2115 . "`naturals`")          ;; ℕ
    (#x2118 . "`weierp`")            ;; ℘
    (#x211a . "`rationals`")         ;; ℚ
    (#x211c . "`real`")              ;; ℜ
    (#x211d . "`reals`")             ;; ℝ
    (#x2122 . "`trade`")             ;; ™
    (#x2124 . "`integers`")          ;; ℤ
    (#x2135 . "`alefsym`")           ;; ℵ
    (#x2190 . "<-")                  ;; ←
    (#x2191 . "`up`")                ;; ↑
    (#x2192 . "->")                  ;; →
    (#x2193 . "`down`")              ;; ↓
    (#x2194 . "`leftright`")         ;; ↔
    (#x2195 . "`updown`")            ;; ↕
    (#x21b2 . "`br`")                ;; ↲
    (#x21b5 . "`crarr`")             ;; ↵
    (#x21b9 . "`tab`")               ;; ↹
    (#x21ba . "`ccw`")               ;; ↺
    (#x21bb . "`cw`")                ;; ↻
    (#x21d0 . "<=")                  ;; ⇐
    (#x21d1 . "`Up`")                ;; ⇑
    (#x21d2 . "=>")                  ;; ⇒
    (#x21d3 . "`Down`")              ;; ⇓
    (#x21d4 . "`LeftRight`")         ;; ⇔
    (#x21d5 . "`UpDown`")            ;; ⇕
    (#x2200 . "`forall`")            ;; ∀
    (#x2202 . "`part`")              ;; ∂
    (#x2203 . "`exists`")            ;; ∃
    (#x2205 . "`empty`")             ;; ∅
    (#x2207 . "`gradient`")          ;; ∇
    (#x2208 . "`in`")                ;; ∈
    (#x2209 . "`notin`")             ;; ∉
    (#x220b . "`ni`")                ;; ∋
    (#x220f . "`prod`")              ;; ∏
    (#x2211 . "`sum`")               ;; ∑
    (#x2212 . "`minus`")             ;; −
    (#x2217 . "`lowast`")            ;; ∗
    (#x2218 . "`after`")             ;; ∘
    (#x221a . "`radic`")             ;; √
    (#x221d . "`prop`")              ;; ∝
    (#x221e . "`infinity`")          ;; ∞
    (#x2220 . "`ang`")               ;; ∠
    (#x2227 . "`and`")               ;; ∧
    (#x2228 . "`or`")                ;; ∨
    (#x2229 . "`intersection`")      ;; ∩
    (#x222a . "`union`")             ;; ∪
    (#x222b . "`integral`")          ;; ∫
    (#x2234 . "`there4`")            ;; ∴
    (#x223c . "`sim`")               ;; ∼
    (#x2245 . "~=")                  ;; ≅
    (#x2248 . "~~")                  ;; ≈
    (#x2260 . "/=")                  ;; ≠
    (#x2261 . "`equiv`")             ;; ≡
    (#x2264 . "=<")                  ;; ≤
    (#x2265 . ">=")                  ;; ≥
    (#x2282 . "`subset`")            ;; ⊂
    (#x2283 . "`supset`")            ;; ⊃
    (#x2284 . "`nsub`")              ;; ⊄
    (#x2286 . "`subseteq`")          ;; ⊆
    (#x2287 . "`supseteq`")          ;; ⊇
    (#x2295 . "`oplus`")             ;; ⊕
    (#x2297 . "`otimes`")            ;; ⊗
    (#x22a5 . "`perp`")              ;; ⊥
    (#x22a6 . "|-")                  ;; ⊦
    (#x22a7 . "|=")                  ;; ⊧
    (#x22bb . "`xor`")               ;; ⊻
    (#x22bc . "`nand`")              ;; ⊼
    (#x22bd . "`nor`")               ;; ⊽
    (#x22c5 . "`sdot`")              ;; ⋅
    (#x2308 . "`lceil`")             ;; ⌈
    (#x2309 . "`rceil`")             ;; ⌉
    (#x230a . "`lfloor`")            ;; ⌊
    (#x230b . "`rfloor`")            ;; ⌋
    (#x2329 . "`lang`")              ;; 〈
    (#x232a . "`rang`")              ;; 〉
    (#x23cf . "`esc`")               ;; ⏏
    (#x25ca . "`loz`")               ;; ◊
    (#x2660 . "`spade`")             ;; ♠
    (#x2663 . "`club`")              ;; ♣
    (#x2665 . "`heart`")             ;; ♥
    (#x2666 . "<>")                  ;; ♦
))

